### ISSUE TITLE
Help fix problem

### ISSUE THREAD

**Issue by ENOT1KK** [zekroTJA/shinpuru#184]
Help me plase setup bot (OS Debian 9. Node: v14.15.0)
![Безымянный](https://user-images.githubusercontent.com/72111329/97581125-3fa70080-1a05-11eb-95a3-94c752ed0c2c.png)

**Comment by zekroTJA** [comment]
Yeah, the build script is not maintained anymore.

Please download the latest binaries from the [releases](https://github.com/zekroTJA/shinpuru/releases) page or pull the official docker image from [docker hub](https://hub.docker.com/r/zekro/shinpuru).

Generally, it's recommented to use the provided [docker-compose configuration](https://github.com/zekroTJA/shinpuru/blob/master/docker-compose.yml) for an easy setup.

**Comment by ENOT1KK** [comment]
Can I do it without docker?

**Comment by ENOT1KK** [comment]
Can I do it without docker? @zekroTJA

**Comment by zekroTJA** [comment]
Sure. Just download the precompiled binaries, which contain the main binary and the compiled SPA files. These files must be placed in the same directory as the binary, if you want to enable the REST API and web interface. 

Also, keep in mind that it's highly recommendet to use redis with shinpuru to reduce the load on your database.

**Comment by ENOT1KK** [comment]
@zekroTJA Can I have a guide? And then I work with GO for the first time, I previously worked with JS

**Comment by zekroTJA** [comment]
If you dont know how to set up MySQL or redis, please take a look in the docs of these projects. There are well documented guids how to set them up.

And, like I said, you only need to download the archive, extract everything and execute the binary. Then, a config file is created where you put in your configuration and preferences. [Here](https://github.com/zekroTJA/shinpuru/blob/master/config/config.example.yaml) you can find an example configuration with explainations for the values.

Thats why I recommend setting up shinpuru with Docker and docker-compose, because you may need a lot of stuff around to use it efficiently.

**Comment by ENOT1KK** [comment]
@zekroTJA I did all of the above, how do I run it on linux now?

**Comment by zekroTJA** [comment]
Did you even read my response?

> And, like I said, you only need to download the archive, extract everything and execute the binary. Then, a config file is created where you put in your configuration and preferences. Here you can find an example configuration with explainations for the values.

**Comment by ENOT1KK** [comment]
@zekroTJA Yes, but then I upload all the files to the server and don't know how to start it.
P.S. I wrote above that this is the first time I work with GO :D

**Comment by SnowLeoo** [comment]
https://github.com/zekroTJA/shinpuru/wiki/Self-Compiling Just read this article.

**Comment by ENOT1KK** [comment]
@zekroTJA It still doesn't work for some reason(((

**Comment by cloudybyte** [comment]
We can't help you if you don't tell us, what your problem is. Also if you haven't used Linux yet, please learn about Linux first.
It's not our job in here to teach you how to use Go/Linux. There are enough sources on the internet to learn.

**Comment by zekroTJA** [comment]
@SnowLeoo The problem is, that the self compiling is not that straight forward and if they don't even know how to execute a binary, this will definetly not be their way.

@ENOT1KK Please look at this gif. Just download the binaries, extract them, execute the shinpuru binary for linux, edit the generated config and re-run the binary.
![](https://i.imgur.com/AXOlyri.gif)

**Comment by ENOT1KK** [comment]
@zekroTJA auth for suite
![Безымянный](https://user-images.githubusercontent.com/72111329/97613406-b6ee8b80-1a29-11eb-841c-527b8f7437ca.png)

**Comment by ENOT1KK** [comment]
Can you also tell me how to add your language to the bot and website?
![Безымянный](https://user-images.githubusercontent.com/72111329/97613938-5c096400-1a2a-11eb-990d-e043fa396440.png)

**Comment by SnowLeoo** [comment]
1. You would have to translate all of the text by yourself.
2. Listen to the Warn of terminal. 
3. Question: Why don't you just invite Shinpuru. It's already hosted

**Comment by ENOT1KK** [comment]
@zekroTJA 1. I want to change some things.
2.this is a valuable experience for me.
3. I understand that manually but the question is where and how.

**Comment by cloudybyte** [comment]
I'm afraid you won't get far with this @ENOT1KK . Shinpurus code is not simple. First learn the language and basic linux things. And then you just have to download the code, modify it and use it. (of course with credit to zekro)
