### ISSUE TITLE
[DOCS] typo in wiki

### ISSUE THREAD

**Issue by cloudybyte** [zekroTJA/shinpuru#195]
## Description
please fix this. saw it a couple of times now and it's really annoying

## Images and Logs
![image](https://user-images.githubusercontent.com/49766357/104289973-09ccd080-54ba-11eb-908d-a9a8ee47c590.png)

**Comment by voxain** [comment]
At least put a trigger warning in the title. Damn.

**Comment by 7h3730B** [comment]
Ah what is that? My eyes are bleeding

**Comment by zekroTJA** [comment]
It even gets worse because the command wiki is autogenerated from the command classes. So, the help in the web UI and the command help has this typo as well. :^)
![image](https://user-images.githubusercontent.com/16734205/104299283-510c8e80-54c5-11eb-9b68-1e76d372440d.png)
![image](https://user-images.githubusercontent.com/16734205/104299343-641f5e80-54c5-11eb-8be0-dd0ce489cd4a.png)

**Comment by cloudybyte** [comment]
reeeeeeeeeeee

**Comment by cloudybyte** [comment]
i think this can be closed?
