### ISSUE TITLE
[FEATURE] shnp personal Karma score

### ISSUE THREAD

**Issue by ShowMeYourSkil** [zekroTJA/shinpuru#240]
## Type of Feature Request

- [ ] New feature
- [x] Enhancement

## Description

List your own Karma score in the web interface. Via the table 'Karma Scoreboard' a table with the title 'Your Karma Score' with your karma points.

## Images and Sketches

![image](https://user-images.githubusercontent.com/39274150/119668142-3107b700-be37-11eb-99b6-17b191dfb62f.png)

**Comment by ShowMeYourSkil** [comment]
*There is a way to read your karma, but I think it is a nice addition.

**Comment by voxain** [comment]
In addition to that, I think it'd make sense not to display it if you're in the top 10 - it should be marked with a color in that case. Otherwise, you could have it sticky at the top.
Also, it'd be awesome if there was a "load more" button at the end of the list - a lot of the time, the lower ranks never get displayed.

**Comment by zekroTJA** [comment]
Do you mean something like that, @ShowMeYourSkil? 
![image](https://user-images.githubusercontent.com/16734205/119670559-454cb380-be39-11eb-95bf-828a7c5bc6c0.png)

Yeah, I think that would be a great idea if you are not displayed in the list already. Also to be consistent with the `karma` command.
![image](https://user-images.githubusercontent.com/16734205/119670739-6e6d4400-be39-11eb-8b48-825954a08968.png)
