### ISSUE TITLE
Bot crashes when mute a user

### ISSUE THREAD

**Issue by LiebesWavezLP** [zekroTJA/shinpuru#325]
### Type

Crash

### Instances

- [ ] Canary
- [ ] Stable
- [X] Self-Hosted

### Description

The bot crashes when i try to mute a user. It wont mute the User and send no feedback.

Shinpuru version: 1.26.1

### Steps to reproduce

1. Use the mute command on a guild to mute a player. For example: ;;mute @test#1234

Then the bot crashes with no feedback or info message and shows only an error in the console log.

### Attachments

Logs of the crash:

panic: runtime error: index out of range [-1]

goroutine 272 [running]:
github.com/zekroTJA/shinpuru/internal/commands.(*CmdMute).muteUnmute(0x1158ca0, {0x1161c48, 0xc00078c3c0})
        /home/runner/work/shinpuru/shinpuru/internal/commands/cmdmute.go:107 +0xb93
github.com/zekroTJA/shinpuru/internal/commands.(*CmdMute).Exec(0xc0000e4cb0, {0x1161c48, 0xc00078c3c0})
        /home/runner/work/shinpuru/shinpuru/internal/commands/cmdmute.go:69 +0x98
github.com/zekroTJA/shireikan.(*handler).messageHandler(0xc0000e4cb0, 0xc00013d500, 0xc0006fd760, 0x0)
        /home/runner/go/pkg/mod/github.com/zekro!t!j!a/shireikan@v0.7.0/handler.go:373 +0x8f1
github.com/zekroTJA/shireikan.(*handler).Setup.func1(0xc00057aa80, 0xc0003fe800)
        /home/runner/go/pkg/mod/github.com/zekro!t!j!a/shireikan@v0.7.0/handler.go:220 +0x28
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc0006787d0, 0x6915ca, {0xecd680, 0xc0008ea6d0})
        /home/runner/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.3-0.20211228023845-29269347e820/eventhandlers.go:518 +0x38
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/runner/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.3-0.20211228023845-29269347e820/event.go:171 +0x172

**Comment by zekroTJA** [comment]
Oh yeah, the command is generally really messed up since the last update. :D
Thank you for the bug report, I'll fix that asap because it could be used to force-shutdown instances of the bot.

But keep in mind that these old commands are kind of in a deprecated state and are replaced by slash commands. If you want to read more about that and what you need to do to use slash commands on your guild, please take a look at the release notes of 1.23.0. :)

https://github.com/zekroTJA/shinpuru/releases/tag/1.23.0

When I have the time to do so, I will also create a wiki article about that specific topic.
