### ISSUE TITLE
Readme Pls add...

### ISSUE THREAD

**Issue by AnimeWolfX** [zekroTJA/shinpuru#371]
### Type

A new feature

### Description

i dont know the Discord.go Start command to start The bot can anybody help?

**Comment by zekroTJA** [comment]
You might want to take a look into the wiki. There you can find information on how to self-host shinpuru.
https://github.com/zekroTJA/shinpuru/wiki/Self-Hosting

I've also created a video where I completely explain all steps required to set up shinpuru using Docker on a server.
https://youtu.be/jCjsL4Mw6a8

**Comment by AnimeWolfX** [comment]
I mean on Replit the start command sry i didnt say that.

**Comment by AnimeWolfX** [comment]
How to start the Bot? Thats what i meant Sry for confusing You

**Comment by zekroTJA** [comment]
Yeah, as I described above, either you use the provided Docker Compose configuration to set up shinpuru on your server together with all services required, which involve MySQL as the database server, Redis for state caching and MinIO for file storage.

Otherwise, you can also simply download the binary from the artifacts section of the [latest release](https://github.com/zekroTJA/shinpuru/releases/tag/1.33.0) for your system architecture, download the [example configuration](https://github.com/zekroTJA/shinpuru/blob/master/config/config.example.yaml), enter your credentials there, put it next to the binary and start the binary of shinpuru. 

The hosting of shinpuru is not that trivial so I honestly recommend that you might want to use one of the official hosts of shinpuru:
https://github.com/zekroTJA/shinpuru/wiki/Invite
